allInfo = [
    "ElectronInfo",
    "ShowerInfo",
    "Pi0Info",
    "PionInfo",
    "EtaInfo",
  #  "OmegaInfo",
    "KsInfo",
    "KaonInfo",
    "PhiInfo",
    "ProtonInfo",
    "LambdaInfo",
    "SigmapInfo",
    "Sigma0Info",
    "XimInfo",
    "Xi0Info",
    "OmegamInfo",
   # "EtaV3PiInfo",
]
